### ISSUE TITLE
does setfont need two parameters?

### ISSUE THREAD

**Issue by increpare** [increpare/zeedonk#322]
we already have font.changesize
I'd recommend dropping the extra parameter from setfont

**Comment by TerryCavanagh** [comment]
Actually, this used to be two commands - changefont and changesize, but I found myself wanting to do both so often that I added the optional parameter to changefont! It's less useful in Zeedonk than it is in Haxegon, since you generally don't want to resize fonts in Zeedonk. Would prefer to keep Zeedonk and Haxegon as consistant as I can, so I'm for keeping it as is.

https://github.com/TerryCavanagh/haxegon/issues/25

**Comment by increpare** [comment]
"Zeedonk. Would prefer to keep Zeedonk and Haxegon as consistant as I can, so I'm for keeping it as is."
Aah I don't like this reasoning! I would like everything to be individually as awesome as possible on their own terms. 

Do we have a zeedonk compiler flag?
